name: R-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.5.1"

      - name: Install base deps
        run: Rscript -e "install.packages(c('testthat','microbenchmark','yaml'), repos='https://cloud.r-project.org')"

      - name: Install project deps (requirements.R)
        run: |
          if [ -f requirements.R ]; then
            Rscript requirements.R
          else
            echo 'No requirements.R file found, skipping'
          fi

      - name: Run tests
        run: Rscript 05_testing_framework/test_runner.R
